version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: espacioevento-frontend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    restart: unless-stopped
    networks:
      - espacioevento-network

networks:
  espacioevento-network:
    driver: bridge
